### ISSUE TITLE
To DreamPiggy

### ISSUE THREAD

**Issue by BeatPlay** [BeatPlay/BetterAmphetaminPlugin#6]
Hey DreamPiggy, i accidently deletet my scePower_stub.a and now i only find the version which doesnt include XBAR, could you link me yours?

**Comment by dreampiggy** [comment]
I'm using a Mac(and I found that you use Linux) and there are different library files for different OS. You can the hole vitasdk from their bintary repo : https://bintray.com/vitasdk/vitasdk/toolchain

However, you can also get their latest binary URL from shell script used by: https://github.com/vitadev/vdpm

```shell
get_version () {
  # replace with '5\.4' if you want that version
  GCCVER='4\.9'
  curl "https://bintray.com/package/files/vitasdk/vitasdk/toolchain?order=desc&sort=fileLastModified&basePath=&tab=files" | egrep "\?file_path=vitasdk-gcc-$GCCVER-.*$1-.+\">" -ao | head -n1 | cut -d= -f2 | cut -d'"' -f1
}

echo "Mac URL: https://bintray.com/vitasdk/vitasdk/download_file?file_path=$(get_version mac)"
#echo "Linux URL: https://bintray.com/vitasdk/vitasdk/download_file?file_path=$(get_version linux)"
#echo "Win32 URL: https://bintray.com/vitasdk/vitasdk/download_file?file_path=$(get_version win32)"
```

create a `.sh` file, copy entire script, `chmod +x script.sh; ./script.sh`, you will see the URL. Download and unzip that file and find that file in `vitasdk/arm-vita-eabi/lib`, or you can just update your vitasdk entirely to replace old folder...

**Comment by dreampiggy** [comment]
OK. I misunderstand your issue. It's that means the lastest version vistasdk deprecated that lib ScePower_stub.a ? What's this means...(I don't think it's right because many power function use that library.)

You should first find the binary name from here(filter upload datetime to determine which one to use):
https://bintray.com/vitasdk/vitasdk/toolchain#files

Then, you can download old version vitasdk used the filename you get from here: 
https://dl.bintray.com/vitasdk/vitasdk/

**Comment by BeatPlay** [comment]
Thank you
